---
abstract: 'handle -M and -m options like perl'
author:
  - 'chocolateboy <chocolate@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Module
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Data::Dumper: 0
  Exporter: 0
  Scalar::Util: 0
  constant: 0
resources:
  bugtracker: http://github.com/chocolateboy/Getopt-Module/issues
  repository: http://github.com/chocolateboy/Getopt-Module
version: v0.0.2
x_test_requires:
  Test::More: 0
